"""Tunable knobs for the engine.

Everything the search can be tweaked with lives here so that experimenting
does not require touching the algorithms themselves.
"""

# ---------- time control ----------

# Wall clock a single move may spend thinking. The 42 subject caps a move at
# 0.5s; the rest is the margin the bookkeeping after the search needs, since
# the deadline is only tested between nodes and the last one still has to
# finish.
TIME_BUDGET = 0.40

# Hard ceiling on iterative deepening. The budget, not this, is what normally
# stops the search; it is here so that a position simple enough to be solved
# outright cannot loop forever, and so that no budget goes into depth past
# what the subject asks for.
MAX_DEPTH = 14

# ---------- search space ----------

# Two stones closer than this (Chebyshev distance) belong to the same cluster.
CLUSTER_RADIUS = 3

# Cells added around a cluster's bounding box: the playable border.
WINDOW_MARGIN = 2

# Two windows are merged when the area their union wastes stays below this
# fraction of the union. Higher = fewer, fatter windows.
MAX_WASTE_RATIO = 0.30

# ---------- branching ----------

# Cells the cheap proximity pre-ranking hands over, beyond the number the
# node will actually keep. Every one of them costs a full play/evaluate/undo,
# and it is by far the largest bill the search pays.
#
# The margin is what lets the real ranking overrule the crude one, and a wide
# node needs it: cutting a ten-move node's shortlist from twenty to thirteen
# was measured to lose games. A node keeping two moves does not -- looking at
# twelve candidates to keep two is eleven evaluations spent on a line already
# committed -- so the shortlist never grows past twice the beam.
SHORTLIST_MARGIN = 10

# How far past the cut the shortlist looks for a move that makes or stops a
# long line (see `search_space.shortlist`). Scanning the whole tail is what
# makes a narrow node expensive: with a beam of two the shortlist keeps four
# candidates and the tail is fifty, and it is walked at every node. A cell
# that makes a four always has a stone of that colour immediately beside it,
# so it is never far down a ranking that counts neighbours.
#
# Sixteen is the smallest bound that still answers every position in
# `tests/test_tactics.py`: at twelve the engine misses one of them, at eight
# it misses two.
#
# MEASURED: walking the whole tail instead -- which makes the promotion
# complete, since a cell with no adjacent stone can make no run -- cost a ply
# (budget-bound median 11 to 10 over 32 positions) and lost the shallow
# self-play smoke test. The promotion puts rescued cells *in front of* the
# shortlist, so rescuing every one of them evicts the ordinary good moves
# rather than joining them. Dropped; the five-completing cells, which are few
# and decisive, are rescued separately and without a window.
TACTICAL_TAIL = 16

# A cell making a line this long, for either colour, is never cut from the
# shortlist however unpromising it looks by proximity.
#
# Four, not five. Five is the move that wins on the spot, and promoting only
# those was not enough: the move that *creates* an open four -- extending
# one's own three -- has a single neighbour and ranks below a dozen cells
# sitting alongside the line, so it was being generated by neither side.
# Games then ran to a rapid alignment because nobody saw the winning
# extension until it was already a five.
CRITICAL_RUN = 4


# How many moves a node expands, by its distance from the root -- the beam.
#
# A flat branching cannot reach ten plies. With ten moves per node the tree
# grows by roughly 2.9 per level even after alpha-beta, so ten levels is on
# the order of a hundred thousand nodes: half a minute, against a half-second
# budget. Cutting the branching everywhere does reach ten, and was measured
# to lose 35 games out of 36 -- a node that looks at three moves is blind
# whatever depth it reaches.
#
# The width is not needed everywhere, though. It is needed where the move is
# actually chosen, near the root; deep down, the line is already committed
# and its remaining job is to confirm or refute it. So the beam starts wide
# and narrows with every ply: the top of the tree keeps the full choice, and
# only the tail is thin enough to afford ten levels.
#
# The width is then tuned back up until the depth is only just comfortable.
# Reaching fourteen plies when the subject asks for ten is budget spent on
# depth nobody grades, so plies 1 to 3 were widened from (3, 2, 2) to
# (4, 3, 2): still ten plies or more in every contested position, and 16 wins
# out of 24 against the narrower setting.
#
# It does not buy back everything. Against the wide, shallow engine this one
# grew out of -- ten moves at every ply, four or five plies deep -- it still
# loses 6-18 over 24 games. Width helps a static evaluation more than depth
# does, and no amount of beam tuning changes that; a sharper evaluation
# would. The subject grades depth, so depth is what this is tuned for.
#
# A note on measuring it: both sides are deterministic, so a duel from a
# handful of fixed openings is 12 fixed outcomes rather than 12 samples, and
# swings wildly. The numbers above come from 24 games over 12 varied
# openings; a 12-game run of the same pair gave the opposite answer.
#
# Index by ply, 0 being the root. Anything deeper than the table gets
# `DEEP_BRANCHING`.
BRANCHING_BY_PLY = (16, 4, 3, 2)
DEEP_BRANCHING = 2

# The root is a special case, because it is searched again at every iteration
# and because it is where the answer actually comes from. It does not have to
# keep the same width throughout: the shallow iterations are cheap, so they
# look at every candidate and rank them, and the deep ones -- which is where
# the whole budget goes -- inherit that ranking and only need to re-examine
# the moves that survived it. Narrowing a root that has already been sorted
# by a six-ply search costs far less than starting narrow.
ROOT_NARROWS_AT = 7
ROOT_BRANCHING_DEEP = 8

# ---------- evaluation ----------

# How much heavier the opponent's shapes weigh than one's own.
#
# A symmetric score says an open three of mine is worth exactly as much as an
# open three of theirs, so building one and blocking one come out even. They
# are not even: whoever ignores the other's three loses the tempo, and the
# tempo is the game. Weighting their side up tips the choice towards the
# answer without needing the search to prove it every time.
#
# The evidence for the exact value is thin, and worth saying so: 1.3 won 14
# of 24 games against 1.0, which at that sample size is barely a lean. It is
# kept because the asymmetry is real and the weight costs nothing, not
# because 14-10 settles anything.
DEFENCE_WEIGHT = 1.3

# ---------- transposition table ----------

# Positions kept across the whole game. Each entry is a small tuple, so this
# is a few tens of megabytes at worst; reaching it empties the table.
TABLE_CAPACITY = 600_000
